# Generated by Django 3.1.7 on 2021-03-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciatedQuestion', models.TextField()),
                ('alternatives', models.JSONField()),
                ('trueOrFalse', models.BooleanField(default=False)),
                ('rightAnswer', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')])),
            ],
        ),
    ]
